<?php 
$modelos = [
    "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
    "qwen2.5-7b-instruct.Q4_K_M.gguf",
    "llama-3.1-8b-instruct.Q4_K_M.gguf",
    "deepseek-coder-6.7b-instruct.Q4_K_M.gguf",
    "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
    "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
    "zephyr-7b-beta.Q4_K_M.gguf",
    "neural-chat-7b-v3-3.Q4_K_M.gguf",
    "qwen2.5-1.5b-instruct.Q4_K_M.gguf",
    "codegeex4-all-9b-Q6_K.gguf",
    "mistral-7b-openorca.Q4_K_M.gguf",
    "dolphin-2.6-mistral-7b.Q4_K_M.gguf",
    "orca-2-7b.Q4_K_M.gguf",
    "solar-10.7b-instruct-v1.0.Q4_K_M.gguf",
    "openhermes-2.5-mistral-7b.Q4_K_M.gguf",
    "mythomax-l2-13b.Q5_K_M.gguf",
    "codellama-7b-instruct.Q4_K_M.gguf",
    "phind-codellama-34b-v2.Q4_K_M.gguf",
    "xwin-lm-7b-v0.1.Q4_K_M.gguf",
    "chinese-alpaca-2-7b.Q4_K_M.gguf",
    "guanaco-7b-uncensored.q4_K_M.gguf",
    "Llama-3.2-3B-Instruct-uncensored-Q4_K_M.gguf",
    "Phi-3.5-mini-instruct_Uncensored-Q4_K_M.gguf",
    "Lexi-Llama-3-8B-Uncensored-Q4_K_M.gguf",
    "Llama-3.1-8B-Lexi-Uncensored-Q4_K_M.gguf",
    "Qwen2.5-14B_Uncensored_Instruct-Q4_K_M.gguf",
    "luvGPT_phi3-uncensored-chat-Q4_K_M.gguf"
];

$repositorios = [
    "Llama-3.2-3B-Instruct-Q4_K_M.gguf" => "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF",
    "qwen2.5-7b-instruct.Q4_K_M.gguf" => "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-GGUF",
    "llama-3.1-8b-instruct.Q4_K_M.gguf" => "https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
    "deepseek-coder-6.7b-instruct.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF",
    "Llama-3.2-1B-Instruct-Q4_K_M.gguf" => "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF",
    "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF",
    "zephyr-7b-beta.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF",
    "neural-chat-7b-v3-3.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/neural-chat-7B-v3-3-GGUF",
    "qwen2.5-1.5b-instruct.Q4_K_M.gguf" => "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF",
    "codegeex4-all-9b-Q6_K.gguf" => "https://huggingface.co/bartowski/codegeex4-all-9b-GGUF",
    "mistral-7b-openorca.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-GGUF",
    "dolphin-2.6-mistral-7b.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/dolphin-2.6-mistral-7b-GGUF",
    "orca-2-7b.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/Orca-2-7B-GGUF",
    "solar-10.7b-instruct-v1.0.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/SOLAR-10.7B-Instruct-v1.0-GGUF",
    "openhermes-2.5-mistral-7b.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF",
    "mythomax-l2-13b.Q5_K_M.gguf" => "https://huggingface.co/TheBloke/MythoMax-L2-13B-GGUF",
    "codellama-7b-instruct.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/CodeLlama-7B-Instruct-GGUF",
    "phind-codellama-34b-v2.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-GGUF",
    "xwin-lm-7b-v0.1.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/Xwin-LM-7B-V0.1-GGUF",
    "chinese-alpaca-2-7b.Q4_K_M.gguf" => "https://huggingface.co/TheBloke/chinese-alpaca-2-7B-GGUF",
    "guanaco-7b-uncensored.q4_K_M.gguf" => "https://huggingface.co/TheBloke/Guanaco-7B-Uncensored-GGUF",
    "Llama-3.2-3B-Instruct-uncensored-Q4_K_M.gguf" => "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-uncensored-GGUF",
    "Phi-3.5-mini-instruct_Uncensored-Q4_K_M.gguf" => "https://huggingface.co/bartowski/Phi-3.5-mini-instruct_Uncensored-GGUF",
    "Lexi-Llama-3-8B-Uncensored-Q4_K_M.gguf" => "https://huggingface.co/bartowski/Lexi-Llama-3-8B-Uncensored-GGUF"
];